disk-mirror:
  # 此配置项目代表的就是是否启用 diskMirror 如果设置为 false 则代表不启用，diskMirror 的starter 将不会被加载
  enabled-feature: false
  # 要使用的盘镜适配器类型 在这里默认数值是本地盘镜适配器，具体的适配器 您可以查阅 top.lingyuzhao.diskMirror.core.DiskMirror 类
  adapter-type: "LocalFSAdapter"
  # 要被盘镜管理的目录 用于存储数据的目录 此目录是真实目录
  root-dir: "/DiskMirror"
  # 一般来说 如果对接带第三方文件系统 而非本次文件系统 则此参数则会派上用场，其代表的就是第三方文件系统的地址
  fs-default-fs: "hdfs://localhost:8020/"
  # 当处理之后，如果处理无错误会返回一个结果状态，此数值代表的就是是否正确处理
  ok-value: "ok!!!!"
  # 返回结果的key 返回结果中 结果状态的字段名字
  res-key: "res"
  # 协议前缀，默认为http 不同协议前缀有不同的意义，用于拼接 url
  protocol-prefix: "http://localhost:80/"
  # 参数 可能会派上用场，在不同的适配器中有不同的实现
  params: { }
  # 用户磁盘配额 每个盘镜空间的磁盘最大空间数值，单位是字节
  user-disk-mirror-space-quota: 134217728
  # 安全密钥
  secure-key: ""
  # 指定的几个用户的空间对应的容量
  space-max-size: { }
  # 是否允许覆盖写文件 如果为 true 则代表不允许覆盖写文件，反之则允许覆盖写文件
  not-over-write: true
  # 设置要使用的空间配置方式 目前支持 HashMapper 和 RedisMapper 两种，用于将不同空间的配置信息放到第三方平台
  use-space-config-mode: "HashMapper"
  # redis 配置
  redis-host-port-db: "127.0.0.1:6379:0"
  # redis 密码
  redis-password: "-"
  # 图像文件压缩模块配置
  image-compress-module:
    # 设置位 true 代表启用~ 反之则不启用 不启用的将不会被加载到 diskMirror 中
    enable: true
    # 设置 png 调色板模式 默认是 RGB_8 代表 8 位压缩
    palette-png: "RGB_8"
    # 设置 调色板生成器，默认是 X255
    palette-generator: "X255"
    # 设置是否支持透明 默认是 false
    transparent: false
  # 设置校验模块
  verifications:
    # 设置读取操作中的 sk 校验 这样所有的读取操作都需要经过这个模块了
    - "SkCheckModule$read"
    # 设置写入操作中的 sk 校验 这样所有的写入操作都需要经过这个模块了
    - "SkCheckModule$writer"

